---
- name: get facts playbook
  hosts: nodes
  gather_facts: false
  vars_files:
    - 01b_secret_encrypted.yaml
  tasks:
    - name: print encrypted var
      debug:
        msg: "{{ password }}"
      # no_log: true
