---
- name: get facts playbook
  hosts: nodes
  gather_facts: true
  tasks:
  - name: print ansible local
    debug:
      msg: "{{ ansible_local }}"

  - name: print var2
    debug:
      msg: "{{ ansible_local.ansible_course.grouped_facts1.var2 }}"
