---
- name: set facts playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: set facts task
    set_fact:
      fact1: "value1"

  - name: output fact1
    debug:
      msg: "fact1 - {{ fact1 }}"
