---
- name: list filters
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: max, min and sum filters
      debug:
        msg:
          - "'[ 2, 4, 6, 8, 10, 12 ] | max' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | max }}"
          - "'[ 2, 4, 6, 8, 10, 12 ] | min' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | min }}"
          - "'[ 2, 4, 6, 8, 10, 12 ] | sum' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | sum }}"

    - name: length, first and last filters
      debug:
        msg:
          - "'[ 2, 4, 6, 8, 10, 12 ] | length' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | length }}"
          - "'[ 2, 4, 6, 8, 10, 12 ] | first' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | first }}"
          - "'[ 2, 4, 6, 8, 10, 12 ] | last' result is
            {{ [ 2, 4, 6, 8, 10, 12 ] | last }}"

    - name: reverse and sort filters
      debug:
        msg:
          - "'[ 2, 4, 6, 8, 10 ] | reverse' result is
            {{ [ 2, 4, 6, 8, 10 ] | reverse }}"
          - "'[ 4, 8, 10, 6, 2 ] | sort' result is
            {{ [ 4, 8, 10, 6, 2 ] | sort }}"

    - name: flatten filter
      debug:
        msg:
          - "'[ 2, [4, [6, 8]], 10 ] | flatten' result is
            {{ [ 2, [4, [6, 8]], 10 ] | flatten }}"
