---
- name: other filters
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    my_string: some string with spaces
  tasks:
    - name: SHA1 hash
      debug:
        msg: "'password' in SHA1 -
          {{ 'password' | hash('sha1') }}"

    - name: SHA512 hash
      debug:
        msg: "'password' in SHA512 - 
          {{ 'password' | password_hash('sha512') }}"

    - name: base64encode filters
      debug:
        msg: "âÉïôú encoded - 
          '{{ 'âÉïôú' | b64encode }}'"
    
    - name: base64decode filter
      debug:
        msg: "w6LDicOvw7TDug== decoded - 
          '{{ 'w6LDicOvw7TDug==' | b64decode }}'"

    - name: quote filter
      debug:
        msg: 
          - "{{ my_string }}"
          - "{{ my_string | quote }}"

    - name: Change case of characters
      debug:
        msg:
          - "'Test | lower' result is {{ 'Test' | lower }}"
          - "'Test | upper' result is {{ 'Test' | upper }}"
          - "'test | capitalize' result is {{ 'test' | capitalize }}'"
